### ISSUE TITLE
Singstar mics recognized as single-channel (macos, chrome/safari/firefox)

### ISSUE THREAD

**Issue by Cajivah** [Asvarox/allkaraoke#97] opened 2024-01-04 21:38 UTC
MacBook Pro 2019, Sonoma 14.2.1 (23C71), Intel CPU
Browsers: Chrome 120.0.6099.129, Firefox 121.0 
Original Sony Singstar Microphones, Wireless

Issue: Cannot set both microphones (red and blue) as separate inputs; only blue (first channel) is recognized.
<img width="300" alt="image" src="https://github.com/Asvarox/allkaraoke/assets/16181770/b7d336a4-438b-4f2d-98aa-ee2cef68a16f">

MacOS sound settings and "Audio MIDI Setup" show this input as 2-channel and both mics work properly but AllKaraoke recognizes it as a single-channel input. It turns out that `const channels = device.getCapabilities?.()?.channelCount?.max ?? 1;` falls back to `1` because `getCapabilities` is `undefined`. All devices appear to be of type `MediaDeviceInfo` that doesn't have `getCapabilities` method. 
<img width="1482" alt="image" src="https://github.com/Asvarox/allkaraoke/assets/16181770/97a44458-3c6c-4cdc-b618-70db56457c86">

We managed to fix it temporarily by changing the default value to 2: 
```
// Microphone.ts
const channels = device.getCapabilities?.()?.channelCount?.max ?? 2;
``` 
I wouldn't dare suggest it as a serious solution though :) 
<img width="1482" alt="image" src="https://github.com/Asvarox/allkaraoke/assets/16181770/9dd202f0-086d-4c8f-9709-7f26837eaf16">

Both channels are detected as separate inputs and the game works just fine. 

I'm unfamiliar with the browser's audio API but I will be able to find some time next week to dig deeper and offer my help. Could you please take a look and verify if it's a bug to be fixed?

Kudos to @szymonmatusiak for suggesting the workaround :)

**Comment by Asvarox** [comment] 2024-01-06 08:44
Hey, thanks for the detailed report :) I managed to reproduce the issue, although in my case `getCapabilities` was defined, but the returned object didn't contain `channelCount`. Seems something's changed in the meantime in those APIs (and not for the first time). I'll see what can be done about this

**Comment by Asvarox** [comment] 2024-01-06 12:00
@Cajivah I pushed a fix to prod. It seems to be working for me. Could you let me know if it works for you too when you have time to take a look?

**Comment by Cajivah** [comment] 2024-01-06 12:39
You're the best! Just on time so that I won't have to run localhost:3000 on the party tonight :D Works perfectly, thanks!

**Closed** 2024-01-06 21:10 UTC
